### ISSUE TITLE
Parallel/Distributed Processing

### ISSUE THREAD

**Issue by halsw** [geneticpy/geneticpy#40]
Hello and congratulations for your nice work.

I'm proposing an improvement where None return values are accepted by `ParameterSet.get_score()` and are interpreted as a request to defer processing till the end of a generation, where `Population.evolve()` calls the declared callback function again, asking for a list of fitness scores for the whole generation.

This allows the user the option to implement parallel/distributed processing in the callback function

I've patched the library, as shown below, to work like that and it's an easy modification, so I hope that it can see something like that implemented in your library.

>             graded.append([score, indiv])  # PATCH1 use list instead of tuple to allow modification
>            if score is None:               # PATCH1 deferred computation requested
>                continue                    # PATCH1 no need to check target 
>            if self.is_achieved_target(score):
>                break
>        if score is None:                   # PATCH1 deferred computation requested
>            self.population[0].fn( graded ) # PATCH1 deferred computation callback
>            for x in graded:                # PATCH1 for all population
>                if x[0] is None:            # PATCH1 if values left unprocessed
>                    raise Exception('Loss function returned None.')  # PATCH1 raise exception
>                x[1].score = x[0]           # PATCH1 set scores in individuals

**Comment by brandonschabell** [comment]
Hi @halsw, thanks for raising the issue! I plan on eventually implementing distributed processing out of the box, but I think adding an option for deferred callbacks/asynchronous scoring functions makes a lot of sense in the nearer term. You can expect this added functionality in the next week or so. Thanks for the idea!

**Comment by halsw** [comment]
Thank you :smiley:

**Comment by brandonschabell** [comment]
@halsw The option to use an async scoring function was added with #43 . This will be available in version 1.3.0- this should be available later today. Thanks for the suggestion!
